##############################################################################
# This Python script was generated by Gemini 2.5 Pro, trained by Google.
#
# The script is designed to clean a specific set of data files by addressing
# data quality issues identified during analysis. The cleaning logic, including
# handling of mixed data formats (fixed-width and CSV), removal of duplicates,
# and filtering of contaminated records, was developed based on the
# characteristics of the source data.
##############################################################################

import os
import zipfile
import pandas as pd
import io
import logging

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# --- Configuration ---
COLD_SNAP_TEMP_THRESHOLD_K = 275.0
HEAT_WAVE_TEMP_THRESHOLD_K = 298.0
HEAT_COLUMNS = ['start_date', 'end_date', 'centroid_date', 'highest_temperature_k', 'duration_days', 'nerc_id', 'spatial_coverage']
COLD_COLUMNS = ['start_date', 'end_date', 'centroid_date', 'lowest_temperature_k', 'duration_days', 'nerc_id', 'spatial_coverage']

def parse_line(line: str, event_type: str) -> dict | None:
    """
    Parses a single line from a source file.

    This function is designed to be robust to two different formats observed
    in the source data: a concatenated fixed-width format and a standard
    comma-separated (CSV) format. This dual-parsing logic is necessary
    based on the structure of the provided data files.
    """
    line = line.strip()
    if not line or not line[0].isdigit():
        return None

    temp_col_name = 'highest_temperature_k' if event_type == 'heat' else 'lowest_temperature_k'

    try:
        if ',' in line:
            parts = line.split(',')
            if len(parts) != 7:
                logging.warning(f"Skipping malformed CSV line: {line}")
                return None
            start_date_str, end_date_str, centroid_date_str, temp_str, dur_str, nerc_id, cov_str = parts
            if 'NERC' not in nerc_id: return None
            return {
                'start_date': pd.to_datetime(start_date_str), 'end_date': pd.to_datetime(end_date_str),
                'centroid_date': pd.to_datetime(centroid_date_str), temp_col_name: float(temp_str),
                'duration_days': int(dur_str), 'nerc_id': 'NERC', 'spatial_coverage': float(cov_str)
            }
        else:
            start_date = pd.to_datetime(line[0:10])
            end_date = pd.to_datetime(line[10:20])
            duration = (end_date - start_date).days + 1
            duration_len = len(str(duration))
            remainder = line[30:]
            parts = remainder.split('NERC')
            if len(parts) != 2: return None
            temp_duration_str = parts[0]
            spatial_coverage_str = parts[1]
            temperature_str = temp_duration_str[:-duration_len]
            if not temperature_str: return None
            return {
                'start_date': start_date, 'end_date': end_date, 'centroid_date': pd.to_datetime(line[20:30]),
                temp_col_name: float(temperature_str), 'duration_days': duration,
                'nerc_id': 'NERC', 'spatial_coverage': float(spatial_coverage_str)
            }
    except (ValueError, IndexError) as e:
        logging.error(f"Could not parse line: '{line}'. Error: {e}")
        return None

def process_and_clean_csv(content: str, event_type: str, columns: list) -> pd.DataFrame | None:
    """Reads content from a single CSV, cleans it, and returns a DataFrame."""
    records = [parsed_data for line in content.splitlines() if (parsed_data := parse_line(line, event_type))]
    if not records:
        return None

    df = pd.DataFrame(records)
    df.columns = columns
    
    initial_rows = len(df)
    df.drop_duplicates(inplace=True)
    logging.info(f"Removed {initial_rows - len(df)} duplicate records.")

    initial_rows = len(df)
    # Filter for contaminated records, which is necessary because some files
    # contain miscategorized events. For example, warm events are found in cold
    # snap files, and cold events are in heat wave files.
    if event_type == 'heat':
        df = df[df['highest_temperature_k'] >= HEAT_WAVE_TEMP_THRESHOLD_K]
        logging.info(f"Removed {initial_rows - len(df)} contaminated cold records.")
    else:
        df = df[df['lowest_temperature_k'] <= COLD_SNAP_TEMP_THRESHOLD_K]
        logging.info(f"Removed {initial_rows - len(df)} contaminated heat records.")
    
    df.sort_values(by='start_date', inplace=True)
    df.reset_index(drop=True, inplace=True)
    return df

def main():
    """Main function to process zip files from /data/original and save to /data/cleaned."""
    script_dir = os.path.dirname(os.path.realpath(__file__))
    original_data_dir = os.path.abspath(os.path.join(script_dir, '../data/original'))
    cleaned_data_dir = os.path.abspath(os.path.join(script_dir, '../data/cleaned'))
    
    if not os.path.isdir(original_data_dir):
        logging.error(f"Original data directory not found at '{original_data_dir}'.")
        return
        
    os.makedirs(cleaned_data_dir, exist_ok=True)

    for zip_filename in os.listdir(original_data_dir):
        if not zip_filename.endswith(".zip"):
            continue
        
        zip_path = os.path.join(original_data_dir, zip_filename)
        zip_basename = os.path.splitext(zip_filename)[0]

        output_subdir = os.path.join(cleaned_data_dir, zip_basename)
        os.makedirs(output_subdir, exist_ok=True)

        event_type = 'heat' if 'heat_wave' in zip_filename else 'cold'
        columns = HEAT_COLUMNS if event_type == 'heat' else COLD_COLUMNS

        logging.info(f"--- Processing archive: {zip_filename} ---")
        with zipfile.ZipFile(zip_path, 'r') as zf:
            for csv_filename in zf.namelist():
                if not csv_filename.endswith('.csv'):
                    continue
                
                logging.info(f"  -> Processing internal file: {csv_filename}")
                with zf.open(csv_filename, 'r') as f:
                    content = io.TextIOWrapper(f, 'utf-8').read()
                
                cleaned_df = process_and_clean_csv(content, event_type, columns)
                
                if cleaned_df is not None and not cleaned_df.empty:
                    csv_basename = os.path.splitext(csv_filename)[0]
                    output_filename = f"{csv_basename}_cleaned.csv"
                    output_path = os.path.join(output_subdir, output_filename)
                    cleaned_df.to_csv(output_path, index=False)
                    logging.info(f"     Clean data saved to '{output_path}'")
                else:
                    logging.info("     No valid data found after cleaning, no file saved.")

if __name__ == '__main__':
    main()