"""
01_load_and_merge.py — Load and merge ComExDBM NetCDF data sources.

Reads heatwave, fire, drought, and meteorological NetCDF files for each year,
merges them on the shared (time, lat, lon) grid, selects relevant variables,
and saves per-year parquet files for downstream cleaning/engineering.

Also exports a raw daily sample as original_sample.csv for the "original
un-cleaned data" deliverable.

# AI-GENERATED: This script was generated by Claude (Anthropic) and reviewed
# by the Zero Shot Hopefuls team. Prompt: "Write a script to load ComExDBM
# NetCDF data from 4 subdirectories, merge on shared dimensions, select
# relevant variables, and save per-year parquet files."
"""

import os
import sys
import warnings
import numpy as np
import pandas as pd
import xarray as xr

warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DATA_ROOT = os.path.join(REPO_ROOT, "dataset", "ComExDBM_CONUS", "04_OutputData")
OUTPUT_DIR = os.path.join(REPO_ROOT, "zero-shot-hopefuls", "Data")
INTERMEDIATE_DIR = os.path.join(OUTPUT_DIR, "intermediate")

YEARS = list(range(2001, 2021))

# Variables to keep from each data source (V02 naming confirmed via inspection)
HW_VARS = ["tmax", "tmin", "tmean", "HI02", "HI05"]
FIRE_VARS = ["FHS_c9", "maxFRP_c9", "BA_km2"]
DROUGHT_VARS = ["pdsi", "pdsi_category", "spi90d", "spei90d"]
MET_VARS = [
    "air_sfc", "apcp", "soilm", "lhtfl", "shtfl", "rhum_2m",
    "uwnd", "vwnd", "BCOC", "LAI", "NDVI", "FWI",
]


def load_year(year: int) -> pd.DataFrame:
    """Load and merge all four NetCDF sources for a single year.

    Returns a DataFrame with columns: date, lat, lon, + all selected variables.
    Ocean / non-CONUS grid cells (all-NaN temperature) are dropped.
    """
    hw_path = os.path.join(
        DATA_ROOT, "01_HeatWave", f"ComExDBM_{year}_HeatWave_V02.nc"
    )
    fire_path = os.path.join(
        DATA_ROOT, "02_FireData", f"ComExDBM_{year}_Fires_V02.nc"
    )
    drought_path = os.path.join(
        DATA_ROOT, "03_DroughtData", f"ComExDBM_{year}_Drought_V02.nc"
    )
    met_path = os.path.join(
        DATA_ROOT, "04_Meteorological_Variables", f"ComExDBM_{year}_MetVars_V02.nc"
    )

    # AI-GENERATED: Variable selection with xarray to minimize memory.
    # Claude (Anthropic). Prompt: "Open NetCDF and select specific variables."
    hw_ds = xr.open_dataset(hw_path)[HW_VARS]
    fire_ds = xr.open_dataset(fire_path)[FIRE_VARS]
    drought_ds = xr.open_dataset(drought_path)[DROUGHT_VARS]
    met_ds = xr.open_dataset(met_path)[MET_VARS]

    # Merge all sources on shared (time, lat, lon) dimensions
    merged = xr.merge([hw_ds, fire_ds, drought_ds, met_ds])

    # Convert to DataFrame and reset multi-index
    df = merged.to_dataframe().reset_index()

    # Close datasets to free memory
    for ds in [hw_ds, fire_ds, drought_ds, met_ds, merged]:
        ds.close()

    # Rename time column to date for clarity
    df = df.rename(columns={"time": "date"})

    # Drop ocean / non-CONUS cells: rows where tmean is NaN
    # (land cells always have temperature data)
    df = df.dropna(subset=["tmean"])

    return df


def main():
    os.makedirs(INTERMEDIATE_DIR, exist_ok=True)

    print(f"Loading ComExDBM data from: {DATA_ROOT}")
    print(f"Years: {YEARS[0]}-{YEARS[-1]}")
    print(f"Intermediate output: {INTERMEDIATE_DIR}")
    print()

    original_sample_saved = False

    for year in YEARS:
        print(f"  Processing {year}...", end=" ", flush=True)

        df = load_year(year)

        # Save a raw daily sample from the first year for the "original data" deliverable
        if not original_sample_saved:
            sample = df.sample(n=min(1000, len(df)), random_state=42)
            sample_path = os.path.join(OUTPUT_DIR, "original_sample.csv")
            sample.to_csv(sample_path, index=False)
            print(f"\n    Saved original sample ({len(sample)} rows) to {sample_path}")
            original_sample_saved = True

        # Save full year daily data as parquet
        parquet_path = os.path.join(INTERMEDIATE_DIR, f"daily_{year}.parquet")
        df.to_parquet(parquet_path, index=False)

        print(f"{len(df):,} rows, {df.shape[1]} cols")

    print()
    print("Load and merge complete.")
    print(f"Intermediate parquet files saved to: {INTERMEDIATE_DIR}")
    print(f"Original sample saved to: {os.path.join(OUTPUT_DIR, 'original_sample.csv')}")


if __name__ == "__main__":
    main()
