"""
02_clean_and_engineer.py — Clean data and engineer features for compound hazard
forecasting.

Loads per-year daily parquet files from 01_load_and_merge.py, applies data
cleaning, engineers new features, aggregates to weekly resolution, creates
forecast target variables, and saves the final cleaned dataset.

# AI-GENERATED: This script was generated by Claude (Anthropic) and reviewed
# by the Zero Shot Hopefuls team. Prompt: "Write a data cleaning and feature
# engineering script for compound hazard forecasting with weekly aggregation,
# rolling temporal features, and forward-shifted target variables."
"""

import os
import sys
import warnings
import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUTPUT_DIR = os.path.join(REPO_ROOT, "zero-shot-hopefuls", "Data")
INTERMEDIATE_DIR = os.path.join(OUTPUT_DIR, "intermediate")

YEARS = list(range(2001, 2021))

# Fire season months (April through October)
FIRE_SEASON_MONTHS = list(range(4, 11))

# Thresholds for compound event definitions
DROUGHT_CATEGORY_THRESHOLD = 3  # pdsi_category <= 3 means mild drought or worse


# ---------------------------------------------------------------------------
# Cleaning functions
# ---------------------------------------------------------------------------

def clean_year(df: pd.DataFrame, year: int) -> pd.DataFrame:
    """Apply cleaning steps to a single year of daily data.

    Steps:
    1. Log NaN counts per variable
    2. Drop rows where all temperature fields are NaN
    3. Zero-fill fire variables (NaN = no fire activity)
    4. Forward-fill met variables within each grid cell (physical continuity)
    5. Flag and remove physically impossible values
    6. Enforce correct dtypes for categorical/binary fields
    7. Check for duplicates
    """
    n_before = len(df)

    # --- Step 1: Log NaN counts ---
    nan_counts = df.isna().sum()
    nan_cols = nan_counts[nan_counts > 0]
    if len(nan_cols) > 0:
        print(f"    NaN counts for {year}:")
        for col, count in nan_cols.items():
            pct = 100 * count / n_before
            print(f"      {col}: {count:,} ({pct:.1f}%)")

    # --- Step 2: Drop rows where temperature is missing ---
    df = df.dropna(subset=["tmax", "tmin", "tmean"], how="all")

    # --- Step 3: Zero-fill fire variables ---
    # NaN in fire data means no fire was detected at that grid cell on that day
    # AI-GENERATED: Claude (Anthropic). Prompt: "Zero-fill fire columns where
    # NaN represents absence of fire activity."
    fire_cols = ["FHS_c9", "maxFRP_c9", "BA_km2"]
    for col in fire_cols:
        if col in df.columns:
            df[col] = df[col].fillna(0.0)

    # Also forward-fill remaining met vars with small NaN fractions,
    # then fill any remaining with column median
    small_nan_cols = ["air_sfc", "apcp", "lhtfl", "shtfl", "rhum_2m",
                      "uwnd", "vwnd", "pdsi", "pdsi_category", "spi90d", "spei90d"]
    for col in small_nan_cols:
        if col in df.columns and df[col].isna().any():
            df[col] = df.groupby(["lat", "lon"])[col].ffill()
            df[col] = df.groupby(["lat", "lon"])[col].bfill()
            if df[col].isna().any():
                df[col] = df[col].fillna(df[col].median())

    # --- Step 4: Forward-fill then back-fill met variables within each grid cell ---
    # Variables like LAI, NDVI, soil moisture have physical continuity;
    # gaps can be forward-filled then back-filled along time within a grid cell.
    # LAI (~46% NaN) and FWI (~35% NaN) have significant gaps, so we also
    # back-fill to handle NaN at the start of each cell's time series.
    met_fill_cols = ["LAI", "NDVI", "soilm", "BCOC", "FWI"]
    df = df.sort_values(["lat", "lon", "date"])
    for col in met_fill_cols:
        if col in df.columns:
            df[col] = df.groupby(["lat", "lon"])[col].ffill()
            df[col] = df.groupby(["lat", "lon"])[col].bfill()
            # Fill any remaining NaN with 0 (grid cells with no data at all)
            df[col] = df[col].fillna(0.0)

    # --- Step 5: Flag and remove physically impossible values ---
    # AI-GENERATED: Claude (Anthropic). Prompt: "Flag outlier values in climate
    # data: negative precipitation, extreme temperatures, negative fire power."
    outlier_mask = pd.Series(False, index=df.index)

    if "apcp" in df.columns:
        outlier_mask |= df["apcp"] < 0
    if "tmax" in df.columns:
        outlier_mask |= (df["tmax"] < -60) | (df["tmax"] > 60)
    if "tmin" in df.columns:
        outlier_mask |= (df["tmin"] < -60) | (df["tmin"] > 60)
    if "maxFRP_c9" in df.columns:
        outlier_mask |= df["maxFRP_c9"] < 0

    n_outliers = outlier_mask.sum()
    if n_outliers > 0:
        print(f"    Removed {n_outliers} rows with physically impossible values")
        df = df[~outlier_mask]

    # --- Step 6: Enforce dtypes ---
    for col in ["HI02", "HI05"]:
        if col in df.columns:
            df[col] = df[col].fillna(0).astype(int)
    if "pdsi_category" in df.columns:
        df["pdsi_category"] = df["pdsi_category"].fillna(5).astype(int)  # 5 = near normal

    # --- Step 7: Duplicate check ---
    n_dupes = df.duplicated(subset=["date", "lat", "lon"]).sum()
    if n_dupes > 0:
        print(f"    WARNING: {n_dupes} duplicate (date, lat, lon) entries found — dropping")
        df = df.drop_duplicates(subset=["date", "lat", "lon"], keep="first")

    n_after = len(df)
    print(f"    Cleaned: {n_before:,} -> {n_after:,} rows "
          f"({n_before - n_after:,} removed)")

    return df


# ---------------------------------------------------------------------------
# Feature engineering functions
# ---------------------------------------------------------------------------

def engineer_daily_features(df: pd.DataFrame) -> pd.DataFrame:
    """Compute engineered features on daily data (before weekly aggregation).

    Features:
    1. compound_hw_drought: heatwave + drought co-occurrence
    2. fire_during_compound: fire during compound conditions
    3. wind_speed: surface wind speed from U/V components
    4. seasonal_sin, seasonal_cos: cyclical day-of-year encoding
    5. tmean_7d_avg: 7-day rolling mean temperature
    6. drought_trend_14d: 14-day change in PDSI
    7. fwi_7d_max: 7-day rolling max Fire Weather Index
    """
    df = df.sort_values(["lat", "lon", "date"]).copy()

    # --- Feature 1: Compound heatwave + drought ---
    # AI-GENERATED: Claude (Anthropic). Prompt: "Create binary compound event
    # label where heatwave (HI02=1) co-occurs with drought (pdsi_category<=3)."
    df["compound_hw_drought"] = (
        (df["HI02"] == 1) & (df["pdsi_category"] <= DROUGHT_CATEGORY_THRESHOLD)
    ).astype(int)

    # --- Feature 2: Fire during compound conditions ---
    df["fire_during_compound"] = (
        (df["compound_hw_drought"] == 1) & (df["FHS_c9"] > 0)
    ).astype(int)

    # --- Feature 3: Surface wind speed ---
    # AI-GENERATED: Claude (Anthropic). Prompt: "Derive wind speed from U and V
    # wind components using Pythagorean theorem."
    df["wind_speed"] = np.sqrt(df["uwnd"] ** 2 + df["vwnd"] ** 2)

    # --- Feature 4: Seasonal encoding ---
    # AI-GENERATED: Claude (Anthropic). Prompt: "Encode day of year as cyclical
    # sin/cos features to avoid discontinuity at year boundaries."
    day_of_year = df["date"].dt.dayofyear
    df["seasonal_sin"] = np.sin(2 * np.pi * day_of_year / 365)
    df["seasonal_cos"] = np.cos(2 * np.pi * day_of_year / 365)

    # --- Feature 5: 7-day rolling mean temperature ---
    # Computed per grid cell to capture local warming trends
    df["tmean_7d_avg"] = (
        df.groupby(["lat", "lon"])["tmean"]
        .transform(lambda x: x.rolling(7, min_periods=3).mean())
    )

    # --- Feature 6: 14-day drought trend (change in PDSI) ---
    # AI-GENERATED: Claude (Anthropic). Prompt: "Compute 14-day PDSI change per
    # grid cell to capture worsening or improving drought conditions."
    df["drought_trend_14d"] = (
        df.groupby(["lat", "lon"])["pdsi"]
        .transform(lambda x: x.diff(periods=14))
    )

    # --- Feature 7: 7-day rolling max FWI ---
    # Captures persistence of fire-favorable weather conditions
    df["fwi_7d_max"] = (
        df.groupby(["lat", "lon"])["FWI"]
        .transform(lambda x: x.rolling(7, min_periods=3).max())
    )

    return df


def aggregate_weekly(df: pd.DataFrame) -> pd.DataFrame:
    """Aggregate daily data to weekly resolution.

    Aggregation rules:
    - Binary indicators (HI02, compound events): weekly max (1 if any day)
    - Continuous variables (temps, met vars): weekly mean
    - Fire counts/area: weekly sum
    - Rolling features: end-of-week value (last)
    """
    # AI-GENERATED: Claude (Anthropic). Prompt: "Aggregate daily climate data to
    # weekly resolution with appropriate aggregation functions per variable type."
    df = df.copy()
    df["year"] = df["date"].dt.isocalendar().year.astype(int)
    df["week"] = df["date"].dt.isocalendar().week.astype(int)

    # Define aggregation rules by variable type
    binary_cols = ["HI02", "HI05", "compound_hw_drought", "fire_during_compound"]
    sum_cols = ["FHS_c9", "BA_km2"]
    last_cols = [
        "tmean_7d_avg", "drought_trend_14d", "fwi_7d_max",
        "seasonal_sin", "seasonal_cos",
    ]

    # Everything else gets averaged
    mean_cols = [
        "tmax", "tmin", "tmean", "air_sfc", "apcp", "soilm", "lhtfl", "shtfl",
        "rhum_2m", "pdsi", "spi90d", "spei90d", "wind_speed",
        "BCOC", "LAI", "NDVI", "FWI", "maxFRP_c9",
    ]

    agg_dict = {}
    for col in binary_cols:
        if col in df.columns:
            agg_dict[col] = "max"
    for col in sum_cols:
        if col in df.columns:
            agg_dict[col] = "sum"
    for col in last_cols:
        if col in df.columns:
            agg_dict[col] = "last"
    for col in mean_cols:
        if col in df.columns:
            agg_dict[col] = "mean"

    # Also keep pdsi_category as the mode (most frequent category that week)
    if "pdsi_category" in df.columns:
        agg_dict["pdsi_category"] = lambda x: x.mode().iloc[0] if len(x.mode()) > 0 else np.nan

    weekly = df.groupby(["lat", "lon", "year", "week"]).agg(agg_dict).reset_index()

    return weekly


def create_target_variables(df: pd.DataFrame) -> pd.DataFrame:
    """Create forecast target variables by shifting compound event labels forward.

    target_compound_1wk: compound_hw_drought value NEXT week (1-week lead)
    target_compound_2wk: compound_hw_drought value 2 weeks ahead
    """
    # AI-GENERATED: Claude (Anthropic). Prompt: "Create forward-shifted target
    # variables for 1-week and 2-week ahead compound hazard forecasting, shifted
    # within each grid cell's time series."
    df = df.sort_values(["lat", "lon", "year", "week"]).copy()

    df["target_compound_1wk"] = (
        df.groupby(["lat", "lon"])["compound_hw_drought"]
        .shift(-1)
    )
    df["target_compound_2wk"] = (
        df.groupby(["lat", "lon"])["compound_hw_drought"]
        .shift(-2)
    )

    return df


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def main():
    print("=" * 60)
    print("Step 2: Clean and Engineer Features")
    print("=" * 60)

    all_weekly = []

    for year in YEARS:
        parquet_path = os.path.join(INTERMEDIATE_DIR, f"daily_{year}.parquet")
        if not os.path.exists(parquet_path):
            print(f"  WARNING: {parquet_path} not found — skipping {year}")
            continue

        print(f"\n  Processing {year}...")

        # Load daily data
        df = pd.read_parquet(parquet_path)
        df["date"] = pd.to_datetime(df["date"])

        # Clean
        df = clean_year(df, year)

        # Engineer daily features (before filtering to fire season so rolling
        # windows at the start of April have January-March data available)
        df = engineer_daily_features(df)

        # Filter to fire season (April-October) AFTER computing rolling features
        df = df[df["date"].dt.month.isin(FIRE_SEASON_MONTHS)]
        print(f"    After fire season filter: {len(df):,} rows")

        # Aggregate to weekly resolution
        weekly = aggregate_weekly(df)
        print(f"    Weekly aggregated: {len(weekly):,} rows")

        all_weekly.append(weekly)

    # Concatenate all years
    print(f"\nConcatenating {len(all_weekly)} years...")
    result = pd.concat(all_weekly, ignore_index=True)
    print(f"  Total weekly rows: {len(result):,}")

    # Create forecast target variables
    result = create_target_variables(result)

    # Drop rows where BOTH targets are NaN (last 1-2 weeks of each grid cell's series)
    n_before = len(result)
    result = result.dropna(subset=["target_compound_1wk"])
    print(f"  After dropping rows without 1wk target: {len(result):,} "
          f"(removed {n_before - len(result):,})")

    # Fill remaining NaN in 2wk target (last week per cell) with 0
    result["target_compound_2wk"] = result["target_compound_2wk"].fillna(0)

    # Ensure binary columns are int
    for col in ["HI02", "HI05", "compound_hw_drought", "fire_during_compound",
                "target_compound_1wk", "target_compound_2wk"]:
        if col in result.columns:
            result[col] = result[col].astype(int)

    # Print class distribution for compound events
    print(f"\n  Compound event distribution (weekly):")
    print(f"    compound_hw_drought=1: "
          f"{result['compound_hw_drought'].sum():,} / {len(result):,} "
          f"({100 * result['compound_hw_drought'].mean():.2f}%)")
    print(f"    fire_during_compound=1: "
          f"{result['fire_during_compound'].sum():,} / {len(result):,} "
          f"({100 * result['fire_during_compound'].mean():.2f}%)")
    print(f"    target_compound_1wk=1: "
          f"{result['target_compound_1wk'].sum():,} / {len(result):,} "
          f"({100 * result['target_compound_1wk'].mean():.2f}%)")

    # Save final cleaned dataset
    output_path = os.path.join(OUTPUT_DIR, "cleaned_compound_hazard_weekly.parquet")
    result.to_parquet(output_path, index=False)
    print(f"\nSaved cleaned dataset: {output_path}")
    print(f"  Shape: {result.shape}")
    print(f"  Columns: {list(result.columns)}")

    print("\nClean and engineer complete.")


if __name__ == "__main__":
    main()
