"""
evaluate.py — Evaluate trained ML models on validation and test sets.

Loads saved models from train.py, optimizes classification thresholds on the
validation set, then evaluates final performance on the held-out test set.
Saves results to ml_results.csv.

# AI-GENERATED: This script was generated by Claude (Anthropic) and reviewed
# by the Zero Shot Hopefuls team. Prompt: "Write an evaluation script that
# loads trained models, optimizes F1 thresholds on validation, evaluates on
# the test set once, and saves metrics to CSV."
"""

import os
import warnings
import numpy as np
import pandas as pd
import joblib
from sklearn.metrics import (
    f1_score, roc_auc_score, precision_score, recall_score,
    brier_score_loss, confusion_matrix,
)

warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DATA_DIR = os.path.join(REPO_ROOT, "zero-shot-hopefuls", "Data")
MODELS_DIR = os.path.join(REPO_ROOT, "zero-shot-hopefuls", "Models")
OUTPUTS_DIR = os.path.join(REPO_ROOT, "zero-shot-hopefuls", "Outputs")
PARQUET_PATH = os.path.join(DATA_DIR, "cleaned_compound_hazard_weekly.parquet")

TARGET_COL = "target_compound_1wk"

FEATURE_COLS = [
    "tmax", "tmin", "tmean", "HI02", "HI05",
    "FHS_c9", "maxFRP_c9", "BA_km2",
    "pdsi", "pdsi_category", "spi90d", "spei90d",
    "air_sfc", "apcp", "soilm", "lhtfl", "shtfl", "rhum_2m",
    "BCOC", "LAI", "NDVI", "FWI",
    "wind_speed", "seasonal_sin", "seasonal_cos",
    "tmean_7d_avg", "drought_trend_14d", "fwi_7d_max",
]

TRAIN_YEARS = list(range(2001, 2016))
VAL_YEARS = list(range(2016, 2018))
TEST_YEARS = list(range(2018, 2021))


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def load_split_data():
    """Load parquet and split into val/test using the same year boundaries."""
    df = pd.read_parquet(PARQUET_PATH)
    val_mask = df["year"].isin(VAL_YEARS)
    test_mask = df["year"].isin(TEST_YEARS)
    return (
        df.loc[val_mask, FEATURE_COLS], df.loc[val_mask, TARGET_COL],
        df.loc[test_mask, FEATURE_COLS], df.loc[test_mask, TARGET_COL],
    )


def find_optimal_threshold(y_true, y_prob):
    """Find the classification threshold that maximizes F1 on the given set.

    With ~4% positive rate, the default 0.5 threshold predicts nearly all
    negatives. This sweeps thresholds to find the F1-optimal operating point.
    """
    # AI-GENERATED: Claude (Anthropic). Prompt: "Find the F1-optimal
    # classification threshold for imbalanced binary classification by
    # sweeping thresholds on a validation set."
    best_f1 = -1
    best_thresh = 0.5
    for thresh in np.arange(0.05, 0.90, 0.01):
        preds = (y_prob >= thresh).astype(int)
        f1 = f1_score(y_true, preds, zero_division=0)
        if f1 > best_f1:
            best_f1 = f1
            best_thresh = thresh
    return best_thresh


def evaluate_model(model_name, y_true, y_prob, threshold):
    """Compute all metrics for a model at the given threshold.

    Returns a dict with F1, AUC-ROC, precision, recall, Brier score, and
    confusion matrix components.
    """
    y_pred = (y_prob >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()

    return {
        "model": model_name,
        "f1": f1_score(y_true, y_pred, zero_division=0),
        "auc_roc": roc_auc_score(y_true, y_prob),
        "precision": precision_score(y_true, y_pred, zero_division=0),
        "recall": recall_score(y_true, y_pred, zero_division=0),
        "brier_score": brier_score_loss(y_true, y_prob),
        "threshold": threshold,
        "tp": int(tp),
        "fp": int(fp),
        "tn": int(tn),
        "fn": int(fn),
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=" * 60)
    print("Week 3: Model Evaluation")
    print("=" * 60)

    os.makedirs(OUTPUTS_DIR, exist_ok=True)

    # Load data
    print("\nLoading data...")
    X_val, y_val, X_test, y_test = load_split_data()
    print(f"  Validation: {len(X_val):,} rows ({y_val.sum():,} positive)")
    print(f"  Test:       {len(X_test):,} rows ({y_test.sum():,} positive)")

    # Load models
    print("\nLoading models...")
    lr_artifact = joblib.load(os.path.join(MODELS_DIR, "logistic_regression.pkl"))
    lr_model = lr_artifact["model"]
    lr_scaler = lr_artifact["scaler"]
    lgb_model = joblib.load(os.path.join(MODELS_DIR, "lightgbm.pkl"))
    print("  Loaded: logistic_regression.pkl, lightgbm.pkl")

    # Get probabilities
    # AI-GENERATED: Claude (Anthropic). Prompt: "Get predicted probabilities
    # from both models, applying the scaler for logistic regression."
    lr_val_prob = lr_model.predict_proba(lr_scaler.transform(X_val))[:, 1]
    lr_test_prob = lr_model.predict_proba(lr_scaler.transform(X_test))[:, 1]
    lgb_val_prob = lgb_model.predict_proba(X_val)[:, 1]
    lgb_test_prob = lgb_model.predict_proba(X_test)[:, 1]

    # Step 1: Optimize thresholds on VALIDATION set only
    print("\nOptimizing thresholds on validation set...")
    lr_thresh = find_optimal_threshold(y_val, lr_val_prob)
    lgb_thresh = find_optimal_threshold(y_val, lgb_val_prob)
    print(f"  Logistic Regression optimal threshold: {lr_thresh:.2f}")
    print(f"  LightGBM optimal threshold:            {lgb_thresh:.2f}")

    # Step 2: Evaluate on both sets
    results = []

    # Validation results
    lr_val = evaluate_model("logistic_regression", y_val, lr_val_prob, lr_thresh)
    lr_val["split"] = "validation"
    results.append(lr_val)

    lgb_val = evaluate_model("lightgbm", y_val, lgb_val_prob, lgb_thresh)
    lgb_val["split"] = "validation"
    results.append(lgb_val)

    # Test results — run once, these are the final numbers
    lr_tst = evaluate_model("logistic_regression", y_test, lr_test_prob, lr_thresh)
    lr_tst["split"] = "test"
    results.append(lr_tst)

    lgb_tst = evaluate_model("lightgbm", y_test, lgb_test_prob, lgb_thresh)
    lgb_tst["split"] = "test"
    results.append(lgb_tst)

    # Save results
    results_df = pd.DataFrame(results)
    col_order = ["model", "split", "f1", "auc_roc", "precision", "recall",
                 "brier_score", "threshold", "tp", "fp", "tn", "fn"]
    results_df = results_df[col_order]
    results_path = os.path.join(OUTPUTS_DIR, "ml_results.csv")
    results_df.to_csv(results_path, index=False)
    print(f"\nSaved: {results_path}")

    # Print formatted summary
    print("\n" + "=" * 60)
    print("Results Summary")
    print("=" * 60)
    print(f"\n{'Model':<25} {'Split':<12} {'F1':>6} {'AUC':>6} "
          f"{'Prec':>6} {'Rec':>6} {'Brier':>6} {'Thresh':>6}")
    print("-" * 80)
    for _, row in results_df.iterrows():
        print(f"{row['model']:<25} {row['split']:<12} "
              f"{row['f1']:>6.4f} {row['auc_roc']:>6.4f} "
              f"{row['precision']:>6.4f} {row['recall']:>6.4f} "
              f"{row['brier_score']:>6.4f} {row['threshold']:>6.2f}")

    print("\nConfusion matrices (TP / FP / TN / FN):")
    for _, row in results_df.iterrows():
        print(f"  {row['model']} ({row['split']}): "
              f"TP={row['tp']:,} FP={row['fp']:,} "
              f"TN={row['tn']:,} FN={row['fn']:,}")

    print("\nEvaluation complete.")


if __name__ == "__main__":
    main()
