"""
interpretability.py — Model interpretability, visualization, and reporting.

Generates SHAP analysis for LightGBM, coefficient plots for Logistic
Regression, and feature importance visualizations. Saves all plots as PNG
files for the Week 3 submission.

# AI-GENERATED: This script was generated by Claude (Anthropic) and reviewed
# by the Zero Shot Hopefuls team. Prompt: "Write an interpretability script
# that produces SHAP summary plots for LightGBM, coefficient bar charts for
# Logistic Regression, and feature importance visualizations, saving each as
# a PNG file."
"""

import os
import warnings
import numpy as np
import pandas as pd
import joblib
import shap
import matplotlib
matplotlib.use("Agg")  # Non-interactive backend for saving plots
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DATA_DIR = os.path.join(REPO_ROOT, "zero-shot-hopefuls", "Data")
MODELS_DIR = os.path.join(REPO_ROOT, "zero-shot-hopefuls", "Models")
VIZ_DIR = os.path.join(REPO_ROOT, "zero-shot-hopefuls", "Visualizations")

PARQUET_PATH = os.path.join(DATA_DIR, "cleaned_compound_hazard_weekly.parquet")

TARGET_COL = "target_compound_1wk"

FEATURE_COLS = [
    "tmax", "tmin", "tmean", "HI02", "HI05",
    "FHS_c9", "maxFRP_c9", "BA_km2",
    "pdsi", "pdsi_category", "spi90d", "spei90d",
    "air_sfc", "apcp", "soilm", "lhtfl", "shtfl", "rhum_2m",
    "BCOC", "LAI", "NDVI", "FWI",
    "wind_speed", "seasonal_sin", "seasonal_cos",
    "tmean_7d_avg", "drought_trend_14d", "fwi_7d_max",
]

TEST_YEARS = list(range(2018, 2021))
SHAP_SAMPLE_SIZE = 5000
RANDOM_STATE = 42


# ---------------------------------------------------------------------------
# Visualization functions
# ---------------------------------------------------------------------------

def plot_lr_coefficients(lr_artifact):
    """Plot Logistic Regression standardized coefficients as a horizontal bar chart.

    Shows which features the linear model weights most heavily, with direction
    (positive = associated with compound event, negative = protective).
    """
    # AI-GENERATED: Claude (Anthropic). Prompt: "Create a horizontal bar chart
    # of logistic regression coefficients sorted by absolute magnitude, color-
    # coded by sign (red = positive, blue = negative)."
    model = lr_artifact["model"]
    coefs = model.coef_[0]

    coef_df = pd.DataFrame({
        "feature": FEATURE_COLS,
        "coefficient": coefs,
    }).sort_values("coefficient", key=abs, ascending=True)

    fig, ax = plt.subplots(figsize=(10, 8))
    colors = ["#d62728" if c > 0 else "#1f77b4" for c in coef_df["coefficient"]]
    ax.barh(coef_df["feature"], coef_df["coefficient"], color=colors)
    ax.set_xlabel("Standardized Coefficient")
    ax.set_title("Logistic Regression: Feature Coefficients\n"
                 "(red = increases compound event risk, blue = decreases)")
    ax.axvline(x=0, color="black", linewidth=0.5)
    plt.tight_layout()

    path = os.path.join(VIZ_DIR, "lr_coefficients.png")
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {path}")


def plot_lgb_feature_importance(lgb_model):
    """Plot LightGBM gain-based feature importance as a horizontal bar chart."""
    importances = lgb_model.feature_importances_
    imp_df = pd.DataFrame({
        "feature": FEATURE_COLS,
        "importance": importances,
    }).sort_values("importance", ascending=True)

    fig, ax = plt.subplots(figsize=(10, 8))
    ax.barh(imp_df["feature"], imp_df["importance"], color="#2ca02c")
    ax.set_xlabel("Feature Importance (split gain)")
    ax.set_title("LightGBM: Feature Importance")
    plt.tight_layout()

    path = os.path.join(VIZ_DIR, "lgb_feature_importance.png")
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {path}")


def plot_shap_summary(lgb_model, X_sample):
    """Generate SHAP beeswarm summary plot for LightGBM.

    Uses TreeExplainer for efficient SHAP computation on a subsample of the
    test set. The beeswarm plot shows both feature importance ranking and
    directional impact (how feature values push predictions).
    """
    # AI-GENERATED: Claude (Anthropic). Prompt: "Compute SHAP values using
    # TreeExplainer for a LightGBM model on a subsample, then create a
    # beeswarm summary plot saved as PNG."
    print("  Computing SHAP values (this may take a minute)...")
    explainer = shap.TreeExplainer(lgb_model)
    shap_values = explainer.shap_values(X_sample)

    # For binary classification, shap_values may be a list [class_0, class_1]
    # or a single array. Use the positive-class values.
    if isinstance(shap_values, list):
        shap_vals = shap_values[1]
    else:
        shap_vals = shap_values

    fig, ax = plt.subplots(figsize=(10, 8))
    shap.summary_plot(shap_vals, X_sample, show=False, max_display=20)
    plt.title("LightGBM: SHAP Feature Impact on Compound Event Prediction")
    plt.tight_layout()

    path = os.path.join(VIZ_DIR, "lgb_shap_summary.png")
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close("all")
    print(f"  Saved: {path}")

    return shap_vals


def plot_shap_dependence(lgb_model, X_sample, shap_vals):
    """Generate SHAP dependence plot for the most important feature.

    Shows how the marginal effect of the top feature varies across its range,
    colored by the feature with the strongest interaction.
    """
    # Find the top feature by mean absolute SHAP value
    mean_abs = np.abs(shap_vals).mean(axis=0)
    top_idx = np.argmax(mean_abs)
    top_feature = FEATURE_COLS[top_idx]
    print(f"  Top SHAP feature: {top_feature}")

    fig, ax = plt.subplots(figsize=(10, 6))
    shap.dependence_plot(top_idx, shap_vals, X_sample, show=False)
    plt.title(f"LightGBM: SHAP Dependence — {top_feature}")
    plt.tight_layout()

    path = os.path.join(VIZ_DIR, "lgb_shap_dependence_top.png")
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close("all")
    print(f"  Saved: {path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=" * 60)
    print("Week 3: Model Interpretability & Visualization")
    print("=" * 60)

    os.makedirs(VIZ_DIR, exist_ok=True)

    # Load data (test set for SHAP analysis)
    print("\nLoading data...")
    df = pd.read_parquet(PARQUET_PATH)
    test_mask = df["year"].isin(TEST_YEARS)
    X_test = df.loc[test_mask, FEATURE_COLS]
    print(f"  Test set: {len(X_test):,} rows")

    # Subsample for SHAP (full test set is too large)
    X_sample = X_test.sample(n=min(SHAP_SAMPLE_SIZE, len(X_test)),
                             random_state=RANDOM_STATE)
    print(f"  SHAP subsample: {len(X_sample):,} rows")

    # Load models
    print("\nLoading models...")
    lr_artifact = joblib.load(os.path.join(MODELS_DIR, "logistic_regression.pkl"))
    lgb_model = joblib.load(os.path.join(MODELS_DIR, "lightgbm.pkl"))

    # Visualization 1: LR Coefficients
    print("\n--- Logistic Regression Coefficients ---")
    plot_lr_coefficients(lr_artifact)

    # Visualization 2: LightGBM Feature Importance
    print("\n--- LightGBM Feature Importance ---")
    plot_lgb_feature_importance(lgb_model)

    # Visualization 3: SHAP Summary (beeswarm)
    print("\n--- SHAP Summary Plot ---")
    shap_vals = plot_shap_summary(lgb_model, X_sample)

    # Visualization 4: SHAP Dependence for top feature
    print("\n--- SHAP Dependence Plot ---")
    plot_shap_dependence(lgb_model, X_sample, shap_vals)

    print("\n" + "=" * 60)
    print("Interpretability complete.")
    print(f"  Visualizations saved to: {VIZ_DIR}")
    print("=" * 60)


if __name__ == "__main__":
    main()
