"""
prepare_llm_subset.py — Sample a test subset and generate ML baseline predictions
for Week 4 LLM benchmarking.

Loads the Week 3 cleaned dataset, filters to the test split (2018-2020),
draws a stratified 1,000-row sample, runs both saved ML models on it,
and saves the result for use in the LLM benchmark notebook.

Also selects few-shot examples from the training set for prompt design.

# AI-GENERATED: This script was generated by Claude (Anthropic) and reviewed
# by the Zero Shot Hopefuls team.
"""

import os
import json
import numpy as np
import pandas as pd
import joblib

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DATA_DIR = os.path.join(REPO_ROOT, "zero-shot-hopefuls", "Data")
MODELS_DIR = os.path.join(REPO_ROOT, "zero-shot-hopefuls", "Models")
PROMPTS_DIR = os.path.join(REPO_ROOT, "zero-shot-hopefuls", "Prompts")
PARQUET_PATH = os.path.join(DATA_DIR, "cleaned_compound_hazard_weekly.parquet")

TARGET_COL = "target_compound_1wk"

FEATURE_COLS = [
    "tmax", "tmin", "tmean", "HI02", "HI05",
    "FHS_c9", "maxFRP_c9", "BA_km2",
    "pdsi", "pdsi_category", "spi90d", "spei90d",
    "air_sfc", "apcp", "soilm", "lhtfl", "shtfl", "rhum_2m",
    "BCOC", "LAI", "NDVI", "FWI",
    "wind_speed", "seasonal_sin", "seasonal_cos",
    "tmean_7d_avg", "drought_trend_14d", "fwi_7d_max",
]

TRAIN_YEARS = list(range(2001, 2016))
TEST_YEARS = list(range(2018, 2021))

# Week 3 optimal thresholds
LR_THRESHOLD = 0.86
LGB_THRESHOLD = 0.65

SAMPLE_SIZE = 1000
RANDOM_STATE = 42


def main():
    print("=" * 60)
    print("Week 4: Prepare LLM Benchmark Subset")
    print("=" * 60)

    # ------------------------------------------------------------------
    # 1. Load dataset and filter to test split
    # ------------------------------------------------------------------
    print("\nLoading dataset...")
    df = pd.read_parquet(PARQUET_PATH)
    print(f"  Full dataset: {df.shape}")

    test_df = df[df["year"].isin(TEST_YEARS)].copy()
    print(f"  Test split (2018-2020): {len(test_df):,} rows, "
          f"{test_df[TARGET_COL].sum():,} positive "
          f"({100 * test_df[TARGET_COL].mean():.2f}%)")

    # ------------------------------------------------------------------
    # 2. Stratified sample of 1,000 rows
    # ------------------------------------------------------------------
    print(f"\nSampling {SAMPLE_SIZE} rows (stratified by {TARGET_COL})...")
    pos = test_df[test_df[TARGET_COL] == 1]
    neg = test_df[test_df[TARGET_COL] == 0]

    pos_rate = len(pos) / len(test_df)
    n_pos = max(1, round(SAMPLE_SIZE * pos_rate))
    n_neg = SAMPLE_SIZE - n_pos

    pos_sample = pos.sample(n=min(n_pos, len(pos)), random_state=RANDOM_STATE)
    neg_sample = neg.sample(n=min(n_neg, len(neg)), random_state=RANDOM_STATE)
    subset = pd.concat([pos_sample, neg_sample]).sample(
        frac=1, random_state=RANDOM_STATE
    ).reset_index(drop=True)

    print(f"  Sampled: {len(subset)} rows | "
          f"{subset[TARGET_COL].sum()} positive "
          f"({100 * subset[TARGET_COL].mean():.2f}%)")

    # ------------------------------------------------------------------
    # 3. Generate ML baseline predictions
    # ------------------------------------------------------------------
    print("\nLoading ML models...")
    lr_artifact = joblib.load(os.path.join(MODELS_DIR, "logistic_regression.pkl"))
    lr_model = lr_artifact["model"]
    lr_scaler = lr_artifact["scaler"]
    lgb_model = joblib.load(os.path.join(MODELS_DIR, "lightgbm.pkl"))

    X_subset = subset[FEATURE_COLS]

    # LR predictions
    lr_prob = lr_model.predict_proba(lr_scaler.transform(X_subset))[:, 1]
    lr_pred = (lr_prob >= LR_THRESHOLD).astype(int)

    # LightGBM predictions
    lgb_prob = lgb_model.predict_proba(X_subset)[:, 1]
    lgb_pred = (lgb_prob >= LGB_THRESHOLD).astype(int)

    subset["ml_lr_probability"] = lr_prob
    subset["ml_lr_prediction"] = lr_pred
    subset["ml_lgb_probability"] = lgb_prob
    subset["ml_lgb_prediction"] = lgb_pred

    # ------------------------------------------------------------------
    # 4. Save subset
    # ------------------------------------------------------------------
    subset_path = os.path.join(DATA_DIR, "llm_test_subset.csv")
    subset.to_csv(subset_path, index=False)
    print(f"\nSaved: {subset_path}")
    print(f"  Columns: {list(subset.columns)}")

    # Quick ML baseline metrics on this subset
    from sklearn.metrics import f1_score, roc_auc_score
    for name, pred, prob in [
        ("Logistic Regression", lr_pred, lr_prob),
        ("LightGBM", lgb_pred, lgb_prob),
    ]:
        f1 = f1_score(subset[TARGET_COL], pred, zero_division=0)
        auc = roc_auc_score(subset[TARGET_COL], prob)
        print(f"  {name} on subset: F1={f1:.4f}, AUC={auc:.4f}")

    # ------------------------------------------------------------------
    # 5. Select few-shot examples from training set
    # ------------------------------------------------------------------
    print("\nSelecting few-shot examples from training set...")
    train_df = df[df["year"].isin(TRAIN_YEARS)].copy()

    # Pick clear positive examples: compound event with strong signals
    pos_train = train_df[train_df[TARGET_COL] == 1].copy()
    pos_train["signal_strength"] = (
        -pos_train["pdsi"]            # lower PDSI = more drought
        + pos_train["tmax"] / 10      # higher temp
        + pos_train["HI02"] * 5       # heatwave active
        + pos_train["FWI"] / 10       # higher fire weather
    )
    strong_pos = pos_train.nlargest(50, "signal_strength").sample(
        n=2, random_state=RANDOM_STATE
    )

    # Pick clear negative examples: no compound event, normal conditions
    neg_train = train_df[train_df[TARGET_COL] == 0].copy()
    neg_train["normality"] = (
        neg_train["pdsi"]              # higher PDSI = wetter
        - neg_train["tmax"] / 10       # lower temp
        + (1 - neg_train["HI02"]) * 5  # no heatwave
    )
    clear_neg = neg_train.nlargest(50, "normality").sample(
        n=3, random_state=RANDOM_STATE
    )

    few_shot_rows = pd.concat([clear_neg, strong_pos]).reset_index(drop=True)

    # Format as JSON
    few_shot_examples = []
    for _, row in few_shot_rows.iterrows():
        example = {
            "features": {col: round(float(row[col]), 4) for col in FEATURE_COLS},
            "label": int(row[TARGET_COL]),
            "metadata": {
                "year": int(row["year"]),
                "week": int(row["week"]),
                "lat": round(float(row["lat"]), 2),
                "lon": round(float(row["lon"]), 2),
            }
        }
        few_shot_examples.append(example)

    os.makedirs(PROMPTS_DIR, exist_ok=True)
    few_shot_path = os.path.join(PROMPTS_DIR, "few_shot_samples.json")
    with open(few_shot_path, "w") as f:
        json.dump(few_shot_examples, f, indent=2)
    print(f"  Saved {len(few_shot_examples)} few-shot examples: {few_shot_path}")
    for i, ex in enumerate(few_shot_examples):
        label = "POSITIVE (compound event)" if ex["label"] == 1 else "NEGATIVE (no event)"
        print(f"    Example {i+1}: {label} | "
              f"pdsi={ex['features']['pdsi']:.2f}, "
              f"tmax={ex['features']['tmax']:.1f}, "
              f"HI02={ex['features']['HI02']}")

    print("\nDone.")


if __name__ == "__main__":
    main()
