"""
train.py — Train and tune ML models for 1-week-ahead compound hazard forecasting.

Loads the cleaned weekly dataset from Week 2, performs a chronological
train/validation/test split, trains a Logistic Regression baseline and a
LightGBM model with hyperparameter tuning, and saves all artifacts.

# AI-GENERATED: This script was generated by Claude (Anthropic) and reviewed
# by the Zero Shot Hopefuls team. Prompt: "Write a training script for binary
# classification of compound heatwave+drought events using chronological
# splitting, Logistic Regression baseline, and LightGBM with hyperparameter
# tuning on a validation set."
"""

import os
import warnings
import numpy as np
import pandas as pd
import joblib
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score, roc_auc_score
from sklearn.model_selection import ParameterSampler
import lightgbm as lgb

warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DATA_DIR = os.path.join(REPO_ROOT, "zero-shot-hopefuls", "Data")
MODELS_DIR = os.path.join(REPO_ROOT, "zero-shot-hopefuls", "Models")
PARQUET_PATH = os.path.join(DATA_DIR, "cleaned_compound_hazard_weekly.parquet")

TARGET_COL = "target_compound_1wk"

# 26 features: physical conditions that drive compound heatwave+drought events.
# Excluded: lat, lon, year, week (identifiers); compound_hw_drought,
# fire_during_compound (definitionally linked to target — autocorrelation
# shortcut); target_compound_1wk, target_compound_2wk (targets).
FEATURE_COLS = [
    # Heatwave variables
    "tmax", "tmin", "tmean", "HI02", "HI05",
    # Fire variables
    "FHS_c9", "maxFRP_c9", "BA_km2",
    # Drought variables
    "pdsi", "pdsi_category", "spi90d", "spei90d",
    # Meteorological variables
    "air_sfc", "apcp", "soilm", "lhtfl", "shtfl", "rhum_2m",
    "BCOC", "LAI", "NDVI", "FWI",
    # Engineered features
    "wind_speed", "seasonal_sin", "seasonal_cos",
    "tmean_7d_avg", "drought_trend_14d", "fwi_7d_max",
]

# Chronological split boundaries — never shuffle time-series data.
# Train on earlier years, validate on middle years, test on most recent.
TRAIN_YEARS = list(range(2001, 2016))  # 2001-2015
VAL_YEARS = list(range(2016, 2018))    # 2016-2017
TEST_YEARS = list(range(2018, 2021))   # 2018-2020

RANDOM_STATE = 42


# ---------------------------------------------------------------------------
# Data loading and splitting
# ---------------------------------------------------------------------------

def load_and_split():
    """Load cleaned dataset and perform chronological train/val/test split.

    Returns X and y for each split, plus saves splits_indexed.csv.
    """
    print("Loading dataset...")
    df = pd.read_parquet(PARQUET_PATH)
    print(f"  Shape: {df.shape}")

    # Assign splits by year
    # AI-GENERATED: Claude (Anthropic). Prompt: "Assign chronological splits
    # by year for time-series data without shuffling."
    conditions = [
        df["year"].isin(TRAIN_YEARS),
        df["year"].isin(VAL_YEARS),
        df["year"].isin(TEST_YEARS),
    ]
    labels = ["train", "val", "test"]
    df["split"] = np.select(conditions, labels, default="unknown")

    # Verify no unknowns
    assert (df["split"] != "unknown").all(), "Some rows not assigned to a split!"

    # Save split index
    splits_path = os.path.join(DATA_DIR, "splits_indexed.csv")
    df[["lat", "lon", "year", "week", "split"]].to_csv(splits_path, index=False)
    print(f"  Saved split index: {splits_path}")

    # Print split statistics
    for split_name in labels:
        mask = df["split"] == split_name
        n = mask.sum()
        pos = df.loc[mask, TARGET_COL].sum()
        rate = 100 * pos / n
        years = sorted(df.loc[mask, "year"].unique())
        print(f"  {split_name:5s}: {n:>10,} rows | {pos:>6,} positive "
              f"({rate:.2f}%) | years {years[0]}-{years[-1]}")

    # Extract features and target for each split
    splits = {}
    for split_name in labels:
        mask = df["split"] == split_name
        X = df.loc[mask, FEATURE_COLS].copy()
        y = df.loc[mask, TARGET_COL].copy()
        splits[split_name] = (X, y)

    X_train, y_train = splits["train"]
    X_val, y_val = splits["val"]
    X_test, y_test = splits["test"]

    return X_train, y_train, X_val, y_val, X_test, y_test


# ---------------------------------------------------------------------------
# Logistic Regression (baseline)
# ---------------------------------------------------------------------------

def train_logistic_regression(X_train, y_train, X_val, y_val):
    """Train L2-regularized Logistic Regression with class balancing.

    Tunes regularization strength C on validation F1.
    """
    # AI-GENERATED: Claude (Anthropic). Prompt: "Train a Logistic Regression
    # baseline with StandardScaler, class_weight='balanced', and C tuning
    # on validation F1 for imbalanced binary classification."
    print("\n" + "=" * 60)
    print("Training Logistic Regression (baseline)")
    print("=" * 60)

    # Scale features — LR needs standardized inputs
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_val_scaled = scaler.transform(X_val)

    # Tune regularization strength C
    C_values = [0.001, 0.01, 0.1, 1.0, 10.0]
    best_f1 = -1
    best_model = None
    best_C = None

    for C in C_values:
        model = LogisticRegression(
            C=C,
            class_weight="balanced",
            solver="saga",
            max_iter=2000,
            random_state=RANDOM_STATE,
            n_jobs=-1,
        )
        model.fit(X_train_scaled, y_train)

        y_prob = model.predict_proba(X_val_scaled)[:, 1]
        y_pred = model.predict(X_val_scaled)
        f1 = f1_score(y_val, y_pred)
        auc = roc_auc_score(y_val, y_prob)
        print(f"  C={C:<6} | Val F1={f1:.4f} | Val AUC={auc:.4f}")

        if f1 > best_f1:
            best_f1 = f1
            best_model = model
            best_C = C

    print(f"  Best C={best_C} | Val F1={best_f1:.4f}")

    # Save model + scaler together
    artifact = {"model": best_model, "scaler": scaler, "best_C": best_C}
    model_path = os.path.join(MODELS_DIR, "logistic_regression.pkl")
    joblib.dump(artifact, model_path)
    print(f"  Saved: {model_path}")

    return best_model, scaler


# ---------------------------------------------------------------------------
# LightGBM (primary model)
# ---------------------------------------------------------------------------

def train_lightgbm(X_train, y_train, X_val, y_val):
    """Train LightGBM with randomized hyperparameter search on validation AUC.

    Uses scale_pos_weight for class imbalance and early stopping to prevent
    overfitting.
    """
    # AI-GENERATED: Claude (Anthropic). Prompt: "Train a LightGBM classifier
    # with scale_pos_weight for 4% class imbalance, randomized hyperparameter
    # search using ParameterSampler, and early stopping on validation AUC."
    print("\n" + "=" * 60)
    print("Training LightGBM (primary)")
    print("=" * 60)

    # Class imbalance weight
    n_neg = (y_train == 0).sum()
    n_pos = (y_train == 1).sum()
    spw = n_neg / n_pos
    print(f"  scale_pos_weight = {spw:.1f} (neg={n_neg:,}, pos={n_pos:,})")

    # Hyperparameter search space
    param_grid = {
        "n_estimators": [300, 500, 800],
        "max_depth": [5, 7, 10],
        "learning_rate": [0.05, 0.1],
        "num_leaves": [31, 63],
        "min_child_samples": [50, 100],
    }

    # Sample 24 random combinations
    n_iter = 24
    sampler = ParameterSampler(param_grid, n_iter=n_iter, random_state=RANDOM_STATE)

    best_auc = -1
    best_model = None
    best_params = None

    for i, params in enumerate(sampler):
        model = lgb.LGBMClassifier(
            **params,
            objective="binary",
            scale_pos_weight=spw,
            random_state=RANDOM_STATE,
            verbose=-1,
            n_jobs=-1,
        )
        model.fit(
            X_train, y_train,
            eval_set=[(X_val, y_val)],
            callbacks=[
                lgb.early_stopping(50, verbose=False),
                lgb.log_evaluation(period=0),
            ],
        )

        y_prob = model.predict_proba(X_val)[:, 1]
        auc = roc_auc_score(y_val, y_prob)
        f1 = f1_score(y_val, model.predict(X_val))

        print(f"  [{i+1:2d}/{n_iter}] AUC={auc:.4f} F1={f1:.4f} | "
              f"lr={params['learning_rate']} depth={params['max_depth']} "
              f"leaves={params['num_leaves']} est={params['n_estimators']} "
              f"mcs={params['min_child_samples']}")

        if auc > best_auc:
            best_auc = auc
            best_model = model
            best_params = params

    print(f"\n  Best AUC={best_auc:.4f}")
    print(f"  Best params: {best_params}")

    # Save model
    model_path = os.path.join(MODELS_DIR, "lightgbm.pkl")
    joblib.dump(best_model, model_path)
    print(f"  Saved: {model_path}")

    return best_model


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=" * 60)
    print("Week 3: ML Model Training")
    print("=" * 60)

    os.makedirs(MODELS_DIR, exist_ok=True)

    # Load and split
    X_train, y_train, X_val, y_val, X_test, y_test = load_and_split()

    # Train both models
    lr_model, lr_scaler = train_logistic_regression(X_train, y_train, X_val, y_val)
    lgb_model = train_lightgbm(X_train, y_train, X_val, y_val)

    print("\n" + "=" * 60)
    print("Training complete.")
    print(f"  Models saved to: {MODELS_DIR}")
    print(f"  Split index saved to: {os.path.join(DATA_DIR, 'splits_indexed.csv')}")
    print("=" * 60)


if __name__ == "__main__":
    main()
